apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipes.agent.serviceName" . }}
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "recipes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
