#!/usr/bin/env bash
# Render a Helm values override that points the chart at Docker Hub images
# under $DOCKER_USER and bakes secrets from backend/.env + agent/.env. Use
# this to deploy a "real" cluster against already-published images (via
# `task push:images` or `task release:images`) — it does NOT push anything
# itself.
#
# Secrets are sourced from backend/.env then agent/.env (agent overrides
# backend) and written into the generated values file. The output lives
# under temp/ and is gitignored — do not check it in.
#
# Env vars:
#   TAG              image tag to deploy (default latest)
#   DOCKER_USER      owner segment of the images (default juancavallotti)
#   REGISTRY         registry hostname (default docker.io — Docker Hub)
#   OUT_FILE         where to write the generated values file
#                    (default temp/values.dockerhub.yaml)
#   INGRESS_ENABLED  enable the ingress in generated values (default true)
#   INGRESS_HOST     ingress host when enabled (default recipes.local)
#   PULL_POLICY      image pull policy (default Always — picks up new
#                    pushes when TAG is a moving tag like "latest")
set -euo pipefail

TAG="${TAG:-latest}"
DOCKER_USER="${DOCKER_USER:-juancavallotti}"
REGISTRY="${REGISTRY:-docker.io}"
OUT_FILE="${OUT_FILE:-temp/values.dockerhub.yaml}"
INGRESS_ENABLED="${INGRESS_ENABLED:-true}"
INGRESS_HOST="${INGRESS_HOST:-recipes.local}"
PULL_POLICY="${PULL_POLICY:-Always}"

case "$INGRESS_ENABLED" in
  true|false) ;;
  *)
    echo "INGRESS_ENABLED must be 'true' or 'false' (got '$INGRESS_ENABLED')" >&2
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

load_env_file() {
  local f="$1"
  if [ -f "$f" ]; then
    echo "==> Loading env from ${f#${REPO_ROOT}/}"
    set -a
    # shellcheck disable=SC1090
    . "$f"
    set +a
  fi
}
load_env_file "$REPO_ROOT/backend/.env"
load_env_file "$REPO_ROOT/agent/.env"

DB_USER="${DB_USER:-postgres}"
DB_PASSWORD="${DB_PASSWORD:-postgres}"
DB_NAME="${DB_NAME:-recipes}"
GEMINI_API_KEY="${GEMINI_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"

if [ -z "$GEMINI_API_KEY" ]; then
  echo "warning: GEMINI_API_KEY not set in agent/.env — agent will fail to start in-cluster." >&2
fi
[ -n "$OPENAI_API_KEY" ]    && echo "==> Including OPENAI_API_KEY in generated secret"
[ -n "$ANTHROPIC_API_KEY" ] && echo "==> Including ANTHROPIC_API_KEY in generated secret"

# docker.io is the default Docker Hub registry; image refs of the form
# "user/name" implicitly resolve to it, so omit the prefix in that case
# to keep the generated values readable.
if [ "$REGISTRY" = "docker.io" ]; then
  REPO_PREFIX="${DOCKER_USER}"
else
  REPO_PREFIX="${REGISTRY}/${DOCKER_USER}"
fi

POSTGRES_REPO="${REPO_PREFIX}/recipes-db"
BACKEND_REPO="${REPO_PREFIX}/recipes-api"
AGENT_REPO="${REPO_PREFIX}/recipes-agent"
WEB_REPO="${REPO_PREFIX}/recipes-web"

mkdir -p "$(dirname "$OUT_FILE")"

# Escape a string for safe inclusion inside a double-quoted YAML scalar.
yaml_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

cat > "$OUT_FILE" <<EOF
# Generated by scripts/dockerhub-values.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Images live on ${REGISTRY} at tag "${TAG}".
# Secrets sourced from backend/.env then agent/.env (agent wins on conflicts).
# Gitignored — do not commit.
postgres:
  image:
    repository: ${POSTGRES_REPO}
    tag: "${TAG}"
    pullPolicy: ${PULL_POLICY}
  auth:
    username: "$(yaml_escape "$DB_USER")"
    password: "$(yaml_escape "$DB_PASSWORD")"
    database: "$(yaml_escape "$DB_NAME")"
backend:
  image:
    repository: ${BACKEND_REPO}
    tag: "${TAG}"
    pullPolicy: ${PULL_POLICY}
agent:
  image:
    repository: ${AGENT_REPO}
    tag: "${TAG}"
    pullPolicy: ${PULL_POLICY}
  geminiApiKeySecret:
    create: true
    value: "$(yaml_escape "$GEMINI_API_KEY")"
  openaiApiKeySecret:
    value: "$(yaml_escape "$OPENAI_API_KEY")"
  anthropicApiKeySecret:
    value: "$(yaml_escape "$ANTHROPIC_API_KEY")"
web:
  image:
    repository: ${WEB_REPO}
    tag: "${TAG}"
    pullPolicy: ${PULL_POLICY}
ingress:
  enabled: ${INGRESS_ENABLED}
  host: "$(yaml_escape "$INGRESS_HOST")"
EOF

echo
echo "Wrote $OUT_FILE"
echo
echo "Deploy with:"
echo "  helm upgrade --install recipes helm -f $OUT_FILE"
