#!/usr/bin/env bash
# Re-tag the locally-built recipes images for ttl.sh, push them, and emit a
# values override file you can pass to `helm upgrade -f`.
#
# ttl.sh is an anonymous, ephemeral OCI registry: images are deleted after the
# TTL embedded in the tag (max 24h). See https://ttl.sh.
#
# Env vars:
#   TTL            ttl.sh expiry tag — e.g. 30m, 1h, 4h, 24h (default 4h)
#   TAG            source image tag to publish (default latest)
#   DOCKER_USER    owner segment of the local images (default juancavallotti)
#   TTLSH_PREFIX   path prefix under ttl.sh/ (default: $DOCKER_USER)
#   TTLSH_REGISTRY override the registry hostname (default ttl.sh)
#   OUT_FILE       where to write the generated values file
#                  (default dist/values.ttlsh.yaml)
set -euo pipefail

TTL="${TTL:-4h}"
SOURCE_TAG="${TAG:-latest}"
DOCKER_USER="${DOCKER_USER:-juancavallotti}"
REGISTRY="${TTLSH_REGISTRY:-ttl.sh}"
PREFIX="${TTLSH_PREFIX:-${DOCKER_USER}}"
OUT_FILE="${OUT_FILE:-dist/values.ttlsh.yaml}"

case "$TTL" in
  *m|*h) ;;
  *)
    echo "TTL must end in 'm' or 'h' (got '$TTL'); e.g. 30m, 1h, 4h, 24h" >&2
    exit 1
    ;;
esac

# Each entry maps a local image name to the helm values key it belongs under.
IMAGES=(
  "recipes-db:postgres"
  "recipes-api:backend"
  "recipes-agent:agent"
  "recipes-web:web"
)

mkdir -p "$(dirname "$OUT_FILE")"

declare -A DEST_REPO
declare -A DEST_TAG

for entry in "${IMAGES[@]}"; do
  name="${entry%%:*}"
  helm_key="${entry##*:}"
  src="${DOCKER_USER}/${name}:${SOURCE_TAG}"
  dest_repo="${REGISTRY}/${PREFIX}/${name}"
  dest_ref="${dest_repo}:${TTL}"

  if ! docker image inspect "$src" >/dev/null 2>&1; then
    echo "Local image $src not found — run 'task build:images' first." >&2
    exit 1
  fi

  echo "==> Tagging  $src -> $dest_ref"
  docker tag "$src" "$dest_ref"

  echo "==> Pushing  $dest_ref"
  docker push "$dest_ref"

  DEST_REPO[$helm_key]="$dest_repo"
  DEST_TAG[$helm_key]="$TTL"
done

cat > "$OUT_FILE" <<EOF
# Generated by scripts/ttlsh-publish.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Images are hosted on ${REGISTRY} and expire ${TTL} after push time.
# Re-run \`task publish:ttlsh\` to refresh them before they expire.
postgres:
  image:
    repository: ${DEST_REPO[postgres]}
    tag: "${DEST_TAG[postgres]}"
    pullPolicy: Always
backend:
  image:
    repository: ${DEST_REPO[backend]}
    tag: "${DEST_TAG[backend]}"
    pullPolicy: Always
agent:
  image:
    repository: ${DEST_REPO[agent]}
    tag: "${DEST_TAG[agent]}"
    pullPolicy: Always
web:
  image:
    repository: ${DEST_REPO[web]}
    tag: "${DEST_TAG[web]}"
    pullPolicy: Always
EOF

echo
echo "Wrote $OUT_FILE"
echo
echo "Deploy with:"
echo "  helm upgrade --install recipes helm -f $OUT_FILE"
